using Aletheia.Sdk.Entity;
using Aletheia.Sdk.Operations;
using Shouldly;

namespace Aletheia.Sdk.Program.Entities.Tests;

/// <summary>
/// Unit tests for <see cref="DataRecord"/> — validates entity metadata,
/// identity strategy, attribute presence, and predicate shape.
/// These tests verify what the source generator will produce at build time.
/// </summary>
public sealed class DataRecordTests
{
    [Fact]
    public void Entity_attribute_is_present_with_correct_path()
    {
        var attribute = (EntityAttribute)Attribute.GetCustomAttribute(
            typeof(DataRecord), typeof(EntityAttribute))!;

        attribute.ShouldNotBeNull();
        attribute.Path.ShouldBe("data-records");
    }

    [Fact]
    public void Identity_attribute_uses_random_generator()
    {
        var attribute = (IdentityAttribute)Attribute.GetCustomAttribute(
            typeof(DataRecord), typeof(IdentityAttribute))!;

        attribute.ShouldNotBeNull();
        attribute.Generator.ShouldBe(IdentityGenerator.Random);
    }

    [Fact]
    public void OperationEndpoints_attribute_is_present()
    {
        var attribute = (OperationEndpointsAttribute)Attribute.GetCustomAttribute(
            typeof(DataRecord), typeof(OperationEndpointsAttribute))!;

        attribute.ShouldNotBeNull();
    }

    [Fact]
    public void DataRecord_is_partial_class()
    {
        typeof(DataRecord).IsClass.ShouldBeTrue();
        // Source generator produces the other partial — the fact this compiles
        // at all confirms the generator ran successfully.
    }

    [Fact]
    public void Non_nullable_scalars_are_present_as_properties()
    {
        var type = typeof(DataRecord);

        type.GetProperty("Label")!.PropertyType.ShouldBe(typeof(string));
        type.GetProperty("Active")!.PropertyType.ShouldBe(typeof(bool));
        type.GetProperty("Count")!.PropertyType.ShouldBe(typeof(int));
        type.GetProperty("Serial")!.PropertyType.ShouldBe(typeof(long));
        type.GetProperty("Ratio")!.PropertyType.ShouldBe(typeof(float));
        type.GetProperty("Score")!.PropertyType.ShouldBe(typeof(double));
        type.GetProperty("Amount")!.PropertyType.ShouldBe(typeof(decimal));
        type.GetProperty("EffectiveDate")!.PropertyType.ShouldBe(typeof(DateOnly));
        type.GetProperty("Timestamp")!.PropertyType.ShouldBe(typeof(DateTimeOffset));
        type.GetProperty("CorrelationId")!.PropertyType.ShouldBe(typeof(Guid));
        type.GetProperty("Reference")!.PropertyType.ShouldBe(typeof(Uri));
    }

    [Fact]
    public void Nullable_scalars_are_present_as_nullable_properties()
    {
        var type = typeof(DataRecord);

        type.GetProperty("Notes")!.PropertyType.ShouldBe(typeof(string));
        type.GetProperty("Flagged")!.PropertyType.ShouldBe(typeof(bool?));
        type.GetProperty("Limit")!.PropertyType.ShouldBe(typeof(int?));
        type.GetProperty("Sequence")!.PropertyType.ShouldBe(typeof(long?));
        type.GetProperty("Factor")!.PropertyType.ShouldBe(typeof(float?));
        type.GetProperty("Precision")!.PropertyType.ShouldBe(typeof(double?));
        type.GetProperty("Fee")!.PropertyType.ShouldBe(typeof(decimal?));
        type.GetProperty("ExpiresOn")!.PropertyType.ShouldBe(typeof(DateOnly?));
        type.GetProperty("UpdatedAt")!.PropertyType.ShouldBe(typeof(DateTimeOffset?));
        type.GetProperty("AlternateId")!.PropertyType.ShouldBe(typeof(Guid?));
        type.GetProperty("Homepage")!.PropertyType.ShouldBe(typeof(Uri));
    }

    [Fact]
    public void Predicate_attributes_are_present_on_all_user_defined_properties()
    {
        var type = typeof(DataRecord);

        // Exclude auto-generated properties (Iri, IsIdentitySealed, etc.)
        // that the source generator adds — they don't need [Predicate] attributes.
        var autoGenerated = new HashSet<string>(StringComparer.Ordinal)
        {
            "Iri", "IsIdentitySealed", "IdentityParts"
        };

        foreach (var prop in type.GetProperties())
        {
            if (autoGenerated.Contains(prop.Name))
                continue;

            var attr = Attribute.GetCustomAttribute(prop, typeof(PredicateAttribute));
            attr.ShouldNotBeNull(
                $"Property '{prop.Name}' is missing a [Predicate] attribute.");
        }
    }

    [Fact]
    public void New_instance_has_default_values()
    {
        var record = new DataRecord();

        record.Label.ShouldBe(string.Empty);
        record.Active.ShouldBeFalse();
        record.Count.ShouldBe(0);
        record.Reference.ToString().ShouldBe("https://www.aletheia.arkenforge.de/");
    }
}
