services:
  app:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      EntityRepository__Backend: GraphDb
      GraphDb__BaseUrl: http://graphdb:7200
    env_file: .env.prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_SLUG}-prod.rule=Host(`${APP_SLUG}.katharsis.digital`)"
      - "traefik.http.routers.${APP_SLUG}-prod.entrypoints=websecure"
      - "traefik.http.routers.${APP_SLUG}-prod.tls.certresolver=myresolver"
      - "traefik.http.routers.${APP_SLUG}-prod.middlewares=authentik@docker"
      - "traefik.http.services.${APP_SLUG}-prod.loadbalancer.server.port=8080"
