<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Homestia.Entities</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aletheia.Sdk.Entity" />
    <PackageReference Include="Aletheia.Sdk.Entity.Generators" />
    <PackageReference Include="Aletheia.Sdk.Operations" />
    <PackageReference Include="Aletheia.Sdk.Operations.Generators" />
  </ItemGroup>

</Project>
