classDiagram
    direction TB

    %% ── Ownership ──
    class Agent {
        <<Aletheia.Authentication>>
        +ID : Guid
        +FirstName: string
        +LastName: string
        +Nickname: string
        +Birthday: Date
        +Email: string
        +PhoneNumber: string
        +Address: string
    }
    style Agent fill:#fff3cd,stroke:#f0ad4e,stroke-width:2px,color:#856404

    class Landlord {
        +ID : Guid
    }
    Landlord "n" --> "1" Agent : represented by
    Property "n" --> "1" Landlord  : owned by (owns)


    %% ── Property ──
    class Segmentation {
        <<abstract>>
        +ID : Guid
        +Name : string
        +IsCommonArea : bool
    }
    Segmentation "n" --> "1" Segmentation : is part of (segments into)

    class Property {
        +ID : Guid
        +Name : string
    }
    Property --|> Segmentation
    Property --> PropertyType : classified as
    Property --> RentalModel : rented as
    

    class PropertyType {
        <<enumeration>>
        Apartment
        Studio
    }

    class RentalModel {
        <<enumeration>>
        EntireProperty
        SingleRoomRentalSharedLiving
    }


    class Room {
    }
    Room --|> Segmentation
    Room --> FurnishingStatus : furnished as
    Room --> RoomStatus : has rental status


    class FurnishingStatus {
        <<enumeration>>
        Unfurnished
        PartiallyFurnished
        FullyFurnished
    }

    %% -- class RoomStatus {
     %% --     <<enumeration>>
     %% --     Available
     %% --    Reserved
      %% --    ActivelyRented
      %% --    Blocked
     %% -- }

    
    %% ── Rental Agreement ──
    class Tenant {
        +ID : Guid
    }
    Tenant "1" --> "1" Agent : extends


    class RentalAgreement {
        +ID : Guid
        +Start: DateTime
        +End: DateTime
        +CreatedAt: DateTime
        +TerminatedAt: DateTime
        +ClosedAt: DateTime
    }
    RentalAgreement "n" --> "1" Tenant : rented by (rents)
    RentalAgreement "1" --> "n" RentalAgreementDocument : has attachments (attached to)
    RentalAgreement "n" --> "n" Segmentation : includes usage of (is part of rental agreement)
    RentalAgreement --> RentalAgreementStatus : has status



    class RentalAgreementDocument {
        <<ObjectBearing>>
        +Description: string
    }


    class RentalAgreementStatus {
        <<enumeration>>
        Preparation
        Signed
        Active
        Terminated
        Handled
        Cancelled
    }


    %% ── To be moved out here ──
    class Entity  {
        <<Sdk.Aletheia.Entity>>
    }

    class CalendarEntry {
        +ID : Guid
        +Start: DateTime  
        +End: DateTime
    }
    CalendarEntry "n" --> "n" Entity : references