// Auto-generated by scripts/generate-entities.mjs — do not edit manually.
// Source: http://localhost:5000/api/entities/entity-definitions
// Generated: 2026-08-28T22:07:21.451Z

import type { EntityInfo } from '../shared/services/aletheia-http-client.models';

export { AgentsEntity, type Agents } from './agents.entity.js';
export { CommonAreaEntity, type CommonArea } from './commonArea.entity.js';
export { FurnishingStatusEntity, type FurnishingStatus } from './furnishingStatus.entity.js';
export { InventoryItemEntity, type InventoryItem } from './inventoryItem.entity.js';
export { LandlordsEntity, type Landlords } from './landlords.entity.js';
export { PropertyEntity, type Property } from './property.entity.js';
export { PropertyTypeEntity, type PropertyType } from './propertyType.entity.js';
export { RentalEntity, type Rental } from './rental.entity.js';
export { RentalModelEntity, type RentalModel } from './rentalModel.entity.js';
export { RentalStageEntity, type RentalStage } from './rentalStage.entity.js';
export { RoomEntity, type Room } from './room.entity.js';
export { RoomStatusEntity, type RoomStatus } from './roomStatus.entity.js';
export { SegmentationsEntity, type Segmentations } from './segmentations.entity.js';
export { StudioEntity, type Studio } from './studio.entity.js';
export { TenantEntity, type Tenant } from './tenant.entity.js';
