// Auto-generated by scripts/generate-entities.mjs — do not edit manually.
// Source: http://localhost:5001/api/entities/entity-definitions
// Generated: 2026-08-21T23:52:34.349Z

import type { EntityInfo } from '../shared/services/aletheia-http-client.models';

export { AgentsEntity, type Agents } from './agents.entity.js';
export { FurnishingStatusEntity, type FurnishingStatus } from './furnishingStatus.entity.js';
export { LandlordsEntity, type Landlords } from './landlords.entity.js';
export { PropertyEntity, type Property } from './property.entity.js';
export { PropertyTypeEntity, type PropertyType } from './propertyType.entity.js';
export { RentalAgreementEntity, type RentalAgreement } from './rentalAgreement.entity.js';
export { RentalAgreementDocumentEntity, type RentalAgreementDocument } from './rentalAgreementDocument.entity.js';
export { RentalAgreementStatusEntity, type RentalAgreementStatus } from './rentalAgreementStatus.entity.js';
export { RentalModelEntity, type RentalModel } from './rentalModel.entity.js';
export { RoomEntity, type Room } from './room.entity.js';
export { RoomStatusEntity, type RoomStatus } from './roomStatus.entity.js';
export { SegmentationsEntity, type Segmentations } from './segmentations.entity.js';
export { TenantsEntity, type Tenants } from './tenants.entity.js';
